#index:
#    path: /
#    controller: App\Controller\DefaultController::index
catalog-versions:
  path: /catalogs-versions
  controller: App\Controller\CatalogsVersions\CatalogsVersionsController::index